apiVersion: v1
kind: Secret
metadata:
  name: {{ include "acct.fullname" . }}-db-secret
  labels:
    {{- include "acct.labels" . | nindent 4 }}
type: Opaque
data:
  DBUSERNAME: {{ .Values.secret.dbUserName | b64enc | quote }}
  DBUSERPWD: {{ .Values.secret.dbUserPwd | b64enc | quote }}
