FROM adoptopenjdk/maven-openjdk11 as build
WORKDIR /build
RUN apt-get update && apt-get install -y git 
RUN git clone https://github.com/harryHagrid/smartbank-modules.git 
RUN cd smartbank-modules && git checkout -b api && git pull origin api
RUN cd /build/smartbank-modules &&  mvn clean package

FROM openjdk-11-jre
COPY --from=build /build/smartbank-modules/target/*.jar app.jar
EXPOSE 8080
ENTRYPOINT ["java"]
CMD ["-jar","app.jar"]
